language: node_js
node_js:
- lts/*
install:
   - npm install
   - ./node_modules/.bin/bower install
before_deploy:
   - rm -rf dist
   - npm run build
   - chmod +x ./deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
