language: node_js
node_js:
  - lts/*
install:
   - npm install
   - ./node_modules/.bin/bower install 
before_deploy:
  - mkdir .ssh
  - openssl aes-256-cbc -K $encrypted_7c488edc362f_key -iv $encrypted_7c488edc362f_iv
  -in www-data.enc -out .ssh/deploy -d
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
