language: node_js
node_js:
- lts/*
before_deploy:
- mkdir .ssh
- openssl aes-256-cbc -K $encrypted_7c488edc362f_key -iv $encrypted_7c488edc362f_iv -in www-data.enc -out ./.ssh/www-data -d
install:
   - npm install
   - ./node_modules/.bin/bower install 
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
